pipeline {
    agent none
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage("Checkout") {
            agent any
            steps {
                checkout scm
                sh "rm -f *.zip"
            }
        }
        stage('Build') {
            agent {
                docker {
                    image 'mcr.microsoft.com/dotnet/sdk:5.0'
                }
            }
            steps {
                sh "dotnet publish --no-self-contained -c Release -r win-x64 -o dist/win-x64 -p:PublishSingleFile=true"
                sh "dotnet publish --no-self-contained -c Release -r linux-x64 -o dist/linux-x64 -p:PublishSingleFile=true"
                zip(zipFile: 'bin-release-win-x64.zip', dir: 'dist/win-x64')
                zip(zipFile: 'bin-release-linux-x64.zip', dir: 'dist/linux-x64')
                stash(name: 'compiled-results', includes: '*.zip')
            }
        }
        stage('Deliver') {
            agent any
            steps {
                dir(path: env.BUILD_ID) { 
                    unstash(name: 'compiled-results') 
                }
            }
            post {
                success {
                    archiveArtifacts "${env.BUILD_ID}/*"
                }
            }
        }
    }
}